### ISSUE TITLE
[6/4 - 6/17] 強化学習のコードとのインターフェイスのフロー図を統合する

### ISSUE THREAD

**Issue by daisukekodaira** [SmartGridLab/der_tester#10]
## 追加したい機能
- 大曽根さんが作った以下の図と #6 で作ったフローチャートの対応を図で表す
<img width="616" alt="330232820-578b994c-b605-452f-9087-17cb32f01b65" src="https://github.com/SmartGridLab/der_tester/assets/43132698/020a8612-cbcc-41c8-b6f6-38be7061e8ef">

上の図の共有URL
[https://boardmix.com/app/share/CAE.CNX6ICAFKhZLQnc3cUZVU0ctYkJUUU9CVGJJWDBnMAVAAQ，リンクをクリックして、Boardmix](https://boardmix.com/app/share/CAE.CNX6ICAFKhZLQnc3cUZVU0ctYkJUUU9CVGJJWDBnMAVAAQ%EF%BC%8C%E3%83%AA%E3%83%B3%E3%82%AF%E3%82%92%E3%82%AF%E3%83%AA%E3%83%83%E3%82%AF%E3%81%97%E3%81%A6%E3%80%81Boardmix) のチーム「私の最初のチーム」に参加してください。

## Issueが解決した時に期待される結果
- 強化学習のコード側から見た司令の何番（①～⑫）が #6 で作ったフローチャートのどれと対応するかが理解できる
- 強化学習とder_testerのコード間のインターフェイス（なんの値をどの関数へいつ渡すのか。戻り値はなにか？）がわかる

## 実装の指針
- 図を作るプラットフォームを統一して作ったほうがよさそう

## このIssueの必要性
- 完成したフローチャートを元に _battery-contro-by-reinforcment-learning_ と _der_tester_ のコードの統合インターフェイスを決めるため
- 強化学習のスケジューリングを実際の蓄電池で動作させるため

## 関連Issue
[#89 der_testerとやりとりするワークフロー図を作る](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/issues/89)

## Issue解決の期限
- 2024/6/7 (初稿）
- 2024/6/14 (第２稿）

**Comment by hayasheesh** [comment]
（軽く見た感じのメモ：１　SOC、操作可否の問い合わせを挟んでから充放電指令を送ることが決まっているので、充放電指令の方では操作可否、SOCのコントロールなどは不要になる。フローチャートとコードの修正が必要。２　スケジュールを実際に使用可能な形式にしたり、遅延を入れて計算したりなどをするなんかのコードが必要かも？　３　電力の計測値はいらない？を[battery-control-by-reinforcement-learning](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning)で見る（スケジュール後にどれくらいのSOCが期待できるかを計算するために必要だと思う）

**Comment by hayasheesh** [comment]
URL先の右側に統合した図を作ってみました。（見た目はまた調整します）

**Comment by daisukekodaira** [comment]
ありがとう。次は大曽根さんと話ながら、強化学習側のコードとのI/Fを決めよう。
6/18にもらった[けんきゅうのーと　6.18まで -.pptx](https://github.com/user-attachments/files/15981365/6.18.-.pptx)を参考に、

- [ ] 強化学習側の最終結果のファイル"Result.csv"の中で、必要な部分を抜き出し、リストにする。
- [ ] 機器側のフィードバックを出力する部分を作る
- [ ] 実際にスケジュール通り動かしてみる
あたりをIssueに登録して整理したい。
