### ISSUE TITLE
[5/20] 定例会向けPPTを作る

### ISSUE THREAD

**Issue by daisukekodaira** [SmartGridLab/der_tester#11]
# やること
#6 でやったことを説明するPPT（2~3枚程度）を作って、ここにアップロードする。

# タスクの経緯
5/22 11:00-11:30 のMTで発表する（説明する）。詳しくは[定例MTG](https://github.com/SmartGridLab/der_tester/milestone/2)を参照。

**Comment by hayasheesh** [comment]
[定例会発表資料.pptx](https://github.com/SmartGridLab/der_tester/files/15343823/default.pptx)
発表資料になります

**Comment by daisukekodaira** [comment]
ありがとう！
