### ISSUE TITLE
[6/12] 第15回需要側電力システム研究会むけPPTを作る

### ISSUE THREAD

**Issue by daisukekodaira** [SmartGridLab/der_tester#12]
##やること
[第15回需要側電力システム研究会](https://github.com/SmartGridLab/der_tester/milestone/1)で発表する資料を作ってここにアップロードする。内容は #6 と #10 で構成する。3-4枚程度。

**Comment by hayasheesh** [comment]
[6・19用.pptx](https://github.com/user-attachments/files/15764727/6.19.pptx)
どこまで詳しく書けばわからなかったのですが、一旦パワポを作ってみました。

**Comment by daisukekodaira** [comment]
ありがとうーーーーー！！見てみます！
