### ISSUE TITLE
[7/31 -> 院試明けまで凍結9/1から再開] 蓄電池の操作を通した手順書の作成(wikiの作成)

### ISSUE THREAD

**Issue by daisukekodaira** [SmartGridLab/der_tester#20]
## 追加したい機能
- 新しい学生や新しい機器を接続するためのドキュメントを作る

## Issueが解決した時に期待される結果
- マークダウン形式。GitHub上で閲覧できるようにする。  
- 実験に新しく参加するメンバーが手順書を読んで、作業が自分できるようになる。  

## 実装の指針
- IoT-EXの柳川さんのサポートを受けながら進める(slackの#蓄電池実証)
- 以下の内容を含める
```
1. (基本編) シナリオベースのワークフロー
[目的] 実験ができるようになる
　・目的の確認（運転モード切り替え、充放電...etc）
　・シナリオを実施するための物理的な条件を確認する方法
　　-> 実験条件と結果の整理のスタイル（フォーマット）を作る
　・条件に一致しない場合にsetする方法
　・各シナリオの具体的なやり方法（運転モードの切り替え、充電指令、放電指令）
　・各シナリオで期待される結果（と期待通りで無い場合の対策）
  　-> 他の学生（知識のない人）にやらせて、マニュアルを検証する

2. (応用編) 仕様を理解する内容（できれば嬉しい）
[目的] 既存以外のシナリオを実証できるようになる。正常系・異常系の判断ができる。トラブルシュートができるようになる。
　・ECHONET Liteの仕様の理解（webAPIの仕様を全て理解する必要は無い。重要な点だけを載せる。）
　・IoT-HUBのwebAPIの仕様の理解
　・pythonコードとのインターフェース（引数・戻り値）の仕様を理解（I/F確認用のテストコードがついている）
　・メーカーへの問い合わせ方法（何をどのように準備すべきなのか？学会発表のときに謝辞にいれる等の対応方法）
　　例）新しい蓄電池と協調的に動作させたいが、どのようにお互いを認識させるのか？ECHONET Liteの仕様は？
```

## このIssueの必要性
実験結果を論文へ書くために以下の内容が必要：  
- 実験結果を客観的にまとめるための手順  
- 実験手順を客観的に説明する文書  

## Issue解決の期限
- 2024/7/15： 柳川さんへ提出
- 2024/7/31：（初版）柳川さんのフィードバックを反映して修正

**Comment by hayasheesh** [comment]
[蓄電池遠隔制御マニュアル_改良版.docx](https://github.com/user-attachments/files/16156396/_.docx)

**Comment by daisukekodaira** [comment]
> [蓄電池遠隔制御マニュアル_改良版.docx](https://github.com/user-attachments/files/16156396/_.docx) 一回自分でマニュアル通り操作してみたところ、レンケイモードにならないとき（この場合があるかどうかはわかりませんが）の対処以外は問題ないと思いました。

ありがとう！確認してみます。

**Comment by daisukekodaira** [comment]
・柳川さんの作ってくれた添付の形式に沿って埋める
・マークダウンでwikiに書いてみる

[整理ポイント一覧.md](https://github.com/user-attachments/files/16188866/default.md)

**Comment by daisukekodaira** [comment]
@hayasheesh 

- 画像の向き
- 目次の番号
- ユーザーシナリオ（充電する場合）

**Comment by hayasheesh** [comment]
完了　電子負荷装置の稼働次第更に更新する必要がある可能性あり
