### ISSUE TITLE
[5/3 - 5/29] 蓄電池の動作を物理的な測定なしで確認するフローを構築する

### ISSUE THREAD

**Issue by daisukekodaira** [SmartGridLab/der_tester#6]
### Discussed in https://github.com/SmartGridLab/der_tester/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **daisukekodaira** April 26, 2024</sup>
## 課題
蓄電池からの通信応答と実動作では差異がある可能性があり、それを検出する必要がある

例）充電確認  
蓄電池にsetコマンドを送り、充電モードへ移行させた場合、getで充電モードであることを確認できるが。しかし、getの応答が充電モードであることと、実際に充電しているかどうかは別の問題である。そのため、数十秒程度(?)の時間をおいて、実電流を取得するgetコマンドを送り、応答の電流値を確認することで実際に充電していることが確認できる。

## 実現したいこと
以下の２点に関して、実動作を実際に測定せずに遠隔から動作と確認し、ログに残す方法をコードで実装する
- 充電動作
- 放電動作

## 実装方針
[Step1] 全体のコマンドの流れ（ワークフロー）を考える 。ワークフロー図を[docs](https://github.com/SmartGridLab/der_tester/tree/master/docs)にいれる。
[Step2] 一部をコードで実行してみる（例：operationMode確認 -> 充電モードへset -> operationMOde確認）  
[Step3] Step1の全体を実装する  
[Step4] コマンド履歴をログ(csv?)に残すようにする  
※現在はset operationModeが動作しないことがわかっている。手動で充電モードへ切り替える。  

ワークフロー図の例：  
![image](https://github.com/SmartGridLab/der_tester/assets/43132698/35b16442-3a01-4952-bdc1-ce4a5367f779)

## 参考文献
海原拓朗，今中政輝，馬場博幸，「DER機器の遠方操作における通信応答と実動作の差異検出支援システムの開発」，電気学会2024年全国大会，4-216，2024.3　[Link](https://drive.google.com/file/d/1H_E7P5UKCnjZzEdbYqpdIi0nRF7NHOmv/view?usp=sharing)</div>

## 期限
[Step1] 5/3  
[Step2] 5/7  
[Step3] 5/21    
[Step4] 5/29  
を目安に

**Comment by hayasheesh** [comment]
docsの方にフローチャートの初稿を入れました。10分置きに命令をし、SOCを20~80%にコントロールする（渡邊さん資料によるとSOC１０％になると停止するのと、SOCが100％になるのを一応防ぐのが数字の理由です）仕様になっています。

**Comment by hayasheesh** [comment]
docsにフローチャートの２稿めを追加しました。
NGの処理、電流値の計測を追加し、反復を5min毎にしました。

**Comment by hayasheesh** [comment]
Step2に入ってみました。getgetset.pyとread_response.pyを追加しました。（自分のレポジトリのところ）
getgetsetではコマンドをセットする手順のところを関数にすることで可読性が高くなると同時に、１回の実行で複数のget/setをすることが容易になりました。
read_response.pyではgetされたresponse_valueを読み込み、それを基に分岐ができるようになりました。

**Comment by daisukekodaira** [comment]
やること：
・フローチャートのルール（ひし形は分岐）に沿った書き方にする
・ユーザーストーリーに沿ったフローチャートを作る（充電するときにフローチャート、放電するときのフローチャートを分けて書く。２枚になる。）

**Comment by hayasheesh** [comment]
Step1:完了しました。3シナリオ共にdocの方に置いてます。
Step2:完了しました。Merge?まで行いました
Step3:完了しました。３つとも実装し、充電シナリオは実機で検証し、大体問題はないことが確認できました。（Setは手動）。Merge？もしました。

**Comment by hayasheesh** [comment]
**時間の記入**

**Comment by hayasheesh** [comment]
プログラムの説明を書く（なんのため、引数、渡数）など

**Comment by hayasheesh** [comment]
setが可能になったことにより、蓄電池の遠隔操作が実際に可能になりました。
蓄電池検証ツール、充放電ツール、SOC確認ツール、待機命令ツール、及びそれらを呼び出すためのmain.pyが作成されました。
また、mergeまで行いました。
